# Generated by Django 5.2.1 on 2025-05-17 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='log_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ects', models.DecimalField(decimal_places=1, max_digits=2)),
                ('sws', models.DecimalField(decimal_places=1, max_digits=2)),
                ('type', models.CharField(choices=[('lecture', 'Lecture'), ('seminar', 'Seminar'), ('tutorial', 'Tutorial'), ('fieldtrip', 'Field Trip'), ('thesis', 'Thesis'), ('external', 'External')], max_length=20)),
                ('max_participants', models.PositiveIntegerField()),
                ('department', models.CharField(max_length=20)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='studyprogrammes.semester')),
            ],
        ),
    ]
