# Generated by Django 5.2.1 on 2025-05-17 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes', '0002_semester_alter_logmessage_log_date_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('degree_type', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('teaching', 'Lehramt')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='programme',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='studyprogrammes.programme'),
            preserve_default=False,
        ),
    ]
