# Generated by Django 5.2.1 on 2025-05-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes', '0003_programme_semester_programme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.CharField(choices=[('PG', 'PG'), ('HG', 'HG')], default='0', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='ects',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='course',
            name='sws',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
