# Generated by Django 5.2.1 on 2025-05-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes', '0004_remove_course_department_course_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='group',
            field=models.CharField(choices=[('PG', 'PG'), ('HG', 'HG'), ('MU', 'Methoden & übergreifend')], max_length=24),
        ),
    ]
