# Generated by Django 5.2.1 on 2025-05-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes', '0005_alter_course_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='semester',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='group',
            field=models.CharField(choices=[('PG', 'PG'), ('HG', 'HG'), ('MU', 'MU')], max_length=24),
        ),
    ]
