# Generated by Django 5.2.1 on 2025-05-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes', '0006_alter_semester_options_semester_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='name',
        ),
    ]
