# Generated by Django 5.2.1 on 2025-05-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes', '0007_remove_semester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ects',
            field=models.IntegerField(),
        ),
    ]
