# Generated by Django 5.2.1 on 2025-05-17 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes', '0009_alter_course_options_course_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='group',
            field=models.CharField(choices=[('PG', 'PG'), ('HG', 'HG'), ('MU', 'MÜ')], max_length=24),
        ),
        migrations.CreateModel(
            name='ProgrammeExpectedStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField()),
                ('degree_type', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('teaching', 'Lehramt')], max_length=20)),
                ('min_students', models.PositiveIntegerField()),
                ('mean_students', models.PositiveIntegerField()),
                ('max_students', models.PositiveIntegerField()),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_students', to='studyprogrammes.programme')),
            ],
            options={
                'ordering': ['programme', 'degree_type', 'semester'],
                'unique_together': {('programme', 'semester', 'degree_type')},
            },
        ),
    ]
