# Generated by Django 5.2.1 on 2025-05-17 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes', '0010_alter_course_group_programmeexpectedstudents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmeexpectedstudents',
            options={'ordering': ['degree_type', 'semester']},
        ),
        migrations.AlterUniqueTogether(
            name='programmeexpectedstudents',
            unique_together={('semester', 'degree_type')},
        ),
        migrations.RemoveField(
            model_name='programmeexpectedstudents',
            name='programme',
        ),
    ]
