# Generated by Django 5.2.1
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('studyprogrammes', '0011_alter_programmeexpectedstudents_options_and_more'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='programmeexpectedstudents',
            name='mean_students',
        ),
    ]
