# Generated by Django 5.2.1 on 2025-05-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes', '0012_remove_mean_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('lecture', 'VL (Vorlesung)'), ('seminar', 'S (Seminar)'), ('tutorial', 'Ü (Übung)'), ('fieldtrip', 'G (Exkursion)'), ('thesis', 'T (Thesis)'), ('external', 'E (Extern)')], max_length=20),
        ),
    ]
