# Generated by Django 5.2.1 on 2025-05-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes', '0014_programme_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
