# Generated by Django 5.2.1 on 2025-05-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes', '0015_programme_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='ects',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='group',
            field=models.CharField(choices=[('PG', 'PG'), ('HG', 'HG'), ('WÜ', 'WÜ'), ('MA', 'MA')], max_length=24),
        ),
    ]
