# Generated by Django 5.0.4 on 2025-07-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes', '0016_programme_order_alter_course_ects_alter_course_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='school_type',
            field=models.CharField(choices=[('elementary', 'Grund-/Mittel-/Realschule'), ('high', 'Gymnasium'), ('didactic', 'Didaktikfach')], default='high', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='group',
            field=models.CharField(choices=[('PG', 'PG'), ('HG', 'HG'), ('WÜ', 'WÜ'), ('MA', 'MA'), ('RG', 'RG'), ('DI', 'DI'), ('EX', 'EX')], max_length=24),
        ),
        migrations.AlterField(
            model_name='programme',
            name='degree_type',
            field=models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('teaching', 'Staatsexamen')], max_length=20),
        ),
        migrations.AlterField(
            model_name='programmeexpectedstudents',
            name='degree_type',
            field=models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('teaching', 'Staatsexamen')], max_length=20),
        ),
    ]
