# Generated by Django 5.0.4 on 2025-07-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes', '0017_programme_school_type_alter_course_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='count_sws',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='school_type',
            field=models.CharField(choices=[('none', 'Keine (BA oder MA)'), ('elementary', 'Grund-/Mittel-/Realschule'), ('high', 'Gymnasium'), ('didactic', 'Didaktikfach')], max_length=40),
        ),
    ]
