# Generated by Django 5.2.1 on 2025-07-08 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ects', models.PositiveIntegerField()),
                ('sws', models.PositiveIntegerField()),
                ('max_participants', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('degree_type', models.CharField(choices=[('bachelor100', 'Bachelor 100'), ('bachelor60', 'Bachelor 60'), ('bachelor30', 'Bachelor 30'), ('teaching_vert', 'Lehramt Vertieft'), ('teaching_nvert', 'Lehramt nicht Vertieft'), ('teaching_gs', 'Lehramt Grundschule'), ('teaching_ms', 'Lehramt Mittelschule'), ('master_pg', 'Master Phys Geo'), ('master_hg', 'Master Humangeo')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('certificate', models.TextField(blank=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='studyprogrammes_v2.programme')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='programme',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='studyprogrammes_v2.revision'),
        ),
        migrations.CreateModel(
            name='ModuleCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_courses', to='studyprogrammes_v2.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_courses', to='studyprogrammes_v2.module')),
            ],
            options={
                'ordering': ['semester', 'order'],
                'unique_together': {('module', 'course', 'semester')},
            },
        ),
    ]
