# Generated by Django 5.2.1 on 2025-07-14 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LPOCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('regional', 'Regional'), ('exkursion', 'Exkursion')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'LPO Category',
                'verbose_name_plural': 'LPO Categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('course_type', models.CharField(choices=[('vorlesung', 'Vorlesung'), ('uebung', 'Übung'), ('seminar', 'Seminar'), ('gelände', 'Geländeseminar'), ('thesis', 'Thesis')], max_length=20)),
                ('discipline', models.CharField(choices=[('physische_geographie', 'Physische Geographie'), ('humangeographie', 'Humangeographie'), ('methoden', 'Methoden'), ('übergreifend', 'Übergreifend')], max_length=25)),
                ('ects', models.PositiveIntegerField(default=6, help_text='ECTS')),
                ('sws', models.PositiveIntegerField(default=2, help_text='Semesterwochenstunden')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('is_shared', models.BooleanField(default=False, help_text='Whether this course is shared with other users')),
                ('shared_at', models.DateTimeField(blank=True, help_text='When this course was shared', null=True)),
                ('original_course', models.ForeignKey(blank=True, help_text='Reference to original course if this is a shared copy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_copies', to='studyprogrammes_v2.course')),
                ('shared_by', models.ForeignKey(blank=True, help_text='Original creator who shared this course', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_courses_v2', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_v2', to=settings.AUTH_USER_MODEL)),
                ('lpo_relevance', models.ManyToManyField(blank=True, help_text='LPO relevance categories', to='studyprogrammes_v2.lpocategory')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField(help_text='Semester number (1, 2, 3, etc.)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of course within this module')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyprogrammes_v2.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within programme')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('certificate', models.TextField(blank=True, help_text='Certificate or qualification information for this module')),
                ('courses', models.ManyToManyField(blank=True, related_name='modules', through='studyprogrammes_v2.CourseModule', to='studyprogrammes_v2.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules_v2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyprogrammes_v2.module'),
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('programme_type', models.CharField(choices=[('bachelor_100', 'Bachelor 100'), ('bachelor_60', 'Bachelor 60'), ('bachelor_30', 'Bachelor 30'), ('lehramt_vertieft', 'Lehramt Vertieft'), ('lehramt_nicht_vertieft', 'Lehramt Nicht Vertieft'), ('lehramt_mittelschule', 'Lehramt Mittelschule'), ('lehramt_grundschule', 'Lehramt Grundschule'), ('master_hg', 'Master Humangeographie'), ('master_pg', 'Master Physische Geographie')], max_length=30)),
                ('comment', models.TextField(blank=True, help_text='Additional notes or comments about this programme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_shared', models.BooleanField(default=False, help_text='Whether this programme is shared with other users')),
                ('shared_at', models.DateTimeField(blank=True, help_text='When this programme was shared', null=True)),
                ('original_programme', models.ForeignKey(blank=True, help_text='Reference to original programme if this is a shared copy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_copies', to='studyprogrammes_v2.programme')),
                ('shared_by', models.ForeignKey(blank=True, help_text='Original creator who shared this programme', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_programmes_v2', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programmes_v2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of module within this programme')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyprogrammes_v2.module')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyprogrammes_v2.programme')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('programme', 'module')},
            },
        ),
        migrations.AddField(
            model_name='programme',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='programmes', through='studyprogrammes_v2.ProgrammeModule', to='studyprogrammes_v2.module'),
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to=settings.AUTH_USER_MODEL)),
                ('programmes', models.ManyToManyField(blank=True, related_name='revisions', to='studyprogrammes_v2.programme')),
            ],
            options={
                'ordering': ['-date', '-order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='coursemodule',
            unique_together={('module', 'course')},
        ),
        migrations.CreateModel(
            name='ProgrammeStudentCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField(help_text='Semester number (1, 2, 3, etc.)')),
                ('min_students', models.PositiveIntegerField(default=0, help_text='Minimum expected students')),
                ('max_students', models.PositiveIntegerField(default=0, help_text='Maximum expected students')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_counts', to='studyprogrammes_v2.programme')),
            ],
            options={
                'ordering': ['programme', 'semester'],
                'unique_together': {('programme', 'semester')},
            },
        ),
    ]
