# Generated by Django 5.2.1 on 2025-07-14 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeNebenfach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField(help_text='Semester number (1, 2, 3, etc.)')),
                ('ects', models.PositiveIntegerField(default=0, help_text='ECTS for minor subject in this semester')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nebenfach_ects', to='studyprogrammes_v2.programme')),
            ],
            options={
                'ordering': ['programme', 'semester'],
                'unique_together': {('programme', 'semester')},
            },
        ),
    ]
