# Generated by Django 5.2.1 on 2025-07-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discipline',
            field=models.CharField(choices=[('human', 'Humangeographie'), ('physical', 'Physische Geographie'), ('methods', 'Methoden'), ('variable', 'Übergreifend'), ('external', 'Extern')], default='human', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('lecture', 'Vorlesung'), ('seminar', 'Seminar'), ('exercise', 'Übung'), ('fieldtrip', 'Exkursion'), ('thesis', 'Abschlussarbeit'), ('other', 'Sonstiges')], default='lecture', max_length=16),
            preserve_default=False,
        ),
    ]
