# Generated by Django 5.2.1 on 2025-07-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0002_course_discipline_course_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revision',
            old_name='user',
            new_name='author',
        ),
    ]
