# Generated by Django 5.2.1 on 2025-07-11 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0003_rename_user_revision_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='programme',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='revision',
            options={'ordering': ['-date', '-order']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='type',
        ),
        migrations.RemoveField(
            model_name='module',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='module',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='degree_type',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='created_at',
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('lecture', 'Vorlesung'), ('seminar', 'Seminar'), ('exercise', 'Übung'), ('fieldtrip', 'Exkursion'), ('thesis', 'Abschlussarbeit'), ('external', 'Extern')], default='lecture', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='lpo_relevance',
            field=models.CharField(blank=True, choices=[('regional', 'Regional'), ('exkursion', 'Exkursion')], help_text='LPO relevance category', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order within lists'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.PositiveIntegerField(default=1, help_text='Recommended semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='modules', to='studyprogrammes_v2.course'),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order within programme'),
        ),
        migrations.AddField(
            model_name='programme',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='programmes', to='studyprogrammes_v2.module'),
        ),
        migrations.AddField(
            model_name='programme',
            name='programme_type',
            field=models.CharField(choices=[('bachelor_100', 'Bachelor 100'), ('bachelor_60', 'Bachelor 60'), ('bachelor_30', 'Bachelor 30'), ('lehramt_vertieft', 'Lehramt Vertieft'), ('lehramt_nicht_vertieft', 'Lehramt nicht Vertieft'), ('lehramt_mittelschule', 'Lehramt Mittelschule'), ('lehramt_grundschule', 'Lehramt Grundschule'), ('master_physische_geographie', 'Master Physische Geographie'), ('master_humangeographie', 'Master Humangeographie')], default='Bachelor100', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revision',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revision',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AddField(
            model_name='revision',
            name='programmes',
            field=models.ManyToManyField(blank=True, related_name='revisions', to='studyprogrammes_v2.programme'),
        ),
        migrations.AlterField(
            model_name='course',
            name='discipline',
            field=models.CharField(choices=[('physical_geography', 'Physische Geographie'), ('human_geography', 'Humangeographie'), ('methods_applied', 'Methoden & Angewandte Geographie'), ('interdisciplinary', 'Interdisziplinär')], max_length=25),
        ),
        migrations.AlterField(
            model_name='course',
            name='ects',
            field=models.PositiveIntegerField(default=6, help_text='ECTS'),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='sws',
            field=models.PositiveIntegerField(default=2, help_text='Semesterwochenstunden'),
        ),
        migrations.DeleteModel(
            name='ModuleCourse',
        ),
    ]
