# Generated by Django 5.2.1 on 2025-07-15 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0003_defaultstudentcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the certificate option', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this certificate option')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in selection lists')),
            ],
            options={
                'verbose_name': 'Certificate Option',
                'verbose_name_plural': 'Certificate Options',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logic_operator', models.CharField(choices=[('and', 'UND'), ('or', 'ODER')], default='or', help_text='How selected options should be combined', max_length=3)),
                ('comment', models.TextField(blank=True, help_text='Additional certificate details or comments')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module_certificate', to='studyprogrammes_v2.module')),
                ('selected_options', models.ManyToManyField(blank=True, help_text='Select multiple certificate options', to='studyprogrammes_v2.certificateoption')),
            ],
            options={
                'verbose_name': 'Module Certificate',
                'verbose_name_plural': 'Module Certificates',
            },
        ),
    ]
