# Generated by Django 5.2.1 on 2025-07-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0004_certificateoption_modulecertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulecertificate',
            name='is_graded',
            field=models.BooleanField(default=True, help_text='Whether this module is graded (benotet) or ungraded (unbenotet)'),
        ),
    ]
