# Generated by Django 5.2.1 on 2025-07-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0004_alter_course_options_alter_module_options_and_more'),
    ]

    operations = [
    ]
