# Generated by Django 5.2.1 on 2025-07-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0005_rebuild_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='LPOCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('regional', 'Regional'), ('exkursion', 'Exkursion')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'LPO Category',
                'verbose_name_plural': 'LPO Categories',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('vorlesung', 'Vorlesung'), ('uebung', 'Übung'), ('seminar', 'Seminar'), ('praktikum', 'Praktikum')], max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='discipline',
            field=models.CharField(choices=[('physische_geographie', 'Physische Geographie'), ('humangeographie', 'Humangeographie'), ('methoden', 'Methoden'), ('übergreifend', 'Übergreifend')], max_length=25),
        ),
        migrations.RemoveField(
            model_name='course',
            name='lpo_relevance',
        ),
        migrations.AlterField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='programme',
            name='programme_type',
            field=models.CharField(choices=[('bachelor_100', 'Bachelor 100'), ('bachelor_60', 'Bachelor 60'), ('bachelor_30', 'Bachelor 30'), ('lehramt_vertieft', 'Lehramt Vertieft'), ('lehramt_nicht_vertieft', 'Lehramt Nicht Vertieft'), ('master_120', 'Master 120'), ('master_60', 'Master 60')], max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='lpo_relevance',
            field=models.ManyToManyField(blank=True, help_text='LPO relevance categories', to='studyprogrammes_v2.lpocategory'),
        ),
    ]
