# Generated by Django 5.2.1 on 2025-07-16 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0005_modulecertificate_is_graded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='original_course',
            field=models.ForeignKey(blank=True, help_text='Reference to original course if this is a shared copy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_copies', to='studyprogrammes_v2.course'),
        ),
    ]
