# Generated by Django 5.2.1 on 2025-07-16 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0006_alter_course_original_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='original_programme',
            field=models.ForeignKey(blank=True, help_text='Reference to original programme if this is a shared copy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_copies', to='studyprogrammes_v2.programme'),
        ),
    ]
