# Generated by Django 5.2.1 on 2025-07-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0006_lpocategory_alter_course_course_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='comment',
            field=models.TextField(blank=True, help_text='Additional notes or comments about this programme'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('vorlesung', 'Vorlesung'), ('uebung', 'Übung'), ('seminar', 'Seminar'), ('gelände', 'Geländeseminar'), ('thesis', 'Thesis')], max_length=20),
        ),
        migrations.AlterField(
            model_name='programme',
            name='programme_type',
            field=models.CharField(choices=[('bachelor_100', 'Bachelor 100'), ('bachelor_60', 'Bachelor 60'), ('bachelor_30', 'Bachelor 30'), ('lehramt_vertieft', 'Lehramt Vertieft'), ('lehramt_nicht_vertieft', 'Lehramt Nicht Vertieft'), ('master_hg', 'Master Phys Geo'), ('master_pg', 'Master Humangeo')], max_length=30),
        ),
    ]
