# Generated by Django 5.2.1 on 2025-07-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0007_alter_programme_original_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultNebenfach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_type', models.CharField(choices=[('bachelor_100', 'Bachelor 100'), ('bachelor_60', 'Bachelor 60'), ('bachelor_30', 'Bachelor 30'), ('lehramt_vertieft', 'Lehramt Vertieft'), ('lehramt_nicht_vertieft', 'Lehramt Nicht Vertieft'), ('lehramt_mittelschule', 'Lehramt Mittelschule'), ('lehramt_grundschule', 'Lehramt Grundschule'), ('master_hg', 'Master Humangeographie'), ('master_pg', 'Master Physische Geographie')], max_length=30)),
                ('semester', models.PositiveIntegerField(help_text='Semester number (1, 2, 3, etc.)')),
                ('ects', models.PositiveIntegerField(default=0, help_text='Default ECTS for minor subject in this semester')),
            ],
            options={
                'verbose_name': 'Default Nebenfach ECTS',
                'verbose_name_plural': 'Default Nebenfach ECTS',
                'ordering': ['programme_type', 'semester'],
                'unique_together': {('programme_type', 'semester')},
            },
        ),
    ]
