# Generated by Django 5.2.1 on 2025-07-12 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0007_programme_comment_alter_course_course_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of module within this programme')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyprogrammes_v2.module')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyprogrammes_v2.programme')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('programme', 'module')},
            },
        ),
    ]
