# Generated by Django 5.2.1 on 2025-07-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0008_defaultnebenfach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpocategory',
            name='name',
            field=models.CharField(choices=[('regional', 'Regional'), ('exkursion', 'Exkursion'), ('didaktik', 'Didaktik')], max_length=20, unique=True),
        ),
    ]
