# Generated by Django 5.2.1 on 2025-07-12 08:57

from django.db import migrations


def populate_programme_modules(apps, schema_editor):
    """Populate ProgrammeModule through table with existing data."""
    Programme = apps.get_model('studyprogrammes_v2', 'Programme')
    ProgrammeModule = apps.get_model('studyprogrammes_v2', 'ProgrammeModule')
    
    # For each programme, create ProgrammeModule entries for existing modules
    for programme in Programme.objects.all():
        for order, module in enumerate(programme.modules.all()):
            ProgrammeModule.objects.create(
                programme=programme,
                module=module,
                order=order  # Use current order as default
            )


def reverse_populate_programme_modules(apps, schema_editor):
    """Clear ProgrammeModule through table."""
    ProgrammeModule = apps.get_model('studyprogrammes_v2', 'ProgrammeModule')
    ProgrammeModule.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0008_add_programmemodule_table'),
    ]

    operations = [
        migrations.RunPython(populate_programme_modules, reverse_populate_programme_modules),
    ]
