# Generated by Django 5.2.1 on 2025-07-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0009_populate_programmemodule_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='modules',
        ),
        migrations.AddField(
            model_name='programme',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='programmes', through='studyprogrammes_v2.ProgrammeModule', to='studyprogrammes_v2.module'),
        ),
    ]
