# Generated by Django 5.2.1 on 2025-07-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0009_alter_lpocategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultnebenfach',
            name='programme_type',
            field=models.CharField(choices=[('bachelor_100', 'Bachelor'), ('bachelor_60', 'Bachelor 60'), ('bachelor_30', 'Bachelor 30'), ('lehramt_vertieft', 'Lehramt Vertieft'), ('lehramt_nicht_vertieft', 'Lehramt Nicht Vertieft'), ('lehramt_mittelschule', 'Lehramt Mittelschule'), ('lehramt_grundschule', 'Lehramt Grundschule'), ('master_hg', 'Master Humangeographie'), ('master_pg', 'Master Physische Geographie')], max_length=30),
        ),
        migrations.AlterField(
            model_name='defaultstudentcount',
            name='programme_type',
            field=models.CharField(choices=[('bachelor_100', 'Bachelor'), ('bachelor_60', 'Bachelor 60'), ('bachelor_30', 'Bachelor 30'), ('lehramt_vertieft', 'Lehramt Vertieft'), ('lehramt_nicht_vertieft', 'Lehramt Nicht Vertieft'), ('lehramt_mittelschule', 'Lehramt Mittelschule'), ('lehramt_grundschule', 'Lehramt Grundschule'), ('master_hg', 'Master Humangeographie'), ('master_pg', 'Master Physische Geographie')], max_length=30),
        ),
        migrations.AlterField(
            model_name='programme',
            name='programme_type',
            field=models.CharField(choices=[('bachelor_100', 'Bachelor'), ('bachelor_60', 'Bachelor 60'), ('bachelor_30', 'Bachelor 30'), ('lehramt_vertieft', 'Lehramt Vertieft'), ('lehramt_nicht_vertieft', 'Lehramt Nicht Vertieft'), ('lehramt_mittelschule', 'Lehramt Mittelschule'), ('lehramt_grundschule', 'Lehramt Grundschule'), ('master_hg', 'Master Humangeographie'), ('master_pg', 'Master Physische Geographie')], max_length=30),
        ),
    ]
