# Generated by Django 5.2.1 on 2025-07-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0010_alter_defaultnebenfach_programme_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='responsible_person',
            field=models.CharField(blank=True, help_text='Modulverantwortliche(r)', max_length=200),
        ),
    ]
