# Generated by Django 5.2.1 on 2025-07-12 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0010_use_through_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeStudentCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField(help_text='Semester number (1, 2, 3, etc.)')),
                ('min_students', models.PositiveIntegerField(default=0, help_text='Minimum expected students')),
                ('max_students', models.PositiveIntegerField(default=0, help_text='Maximum expected students')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_counts', to='studyprogrammes_v2.programme')),
            ],
            options={
                'ordering': ['programme', 'semester'],
                'unique_together': {('programme', 'semester')},
            },
        ),
    ]
