# Generated by Django 5.2.1 on 2025-07-12 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0011_programmestudentcount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_v2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules_v2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programme',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programmes_v2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programme',
            name='programme_type',
            field=models.CharField(choices=[('bachelor_100', 'Bachelor 100'), ('bachelor_60', 'Bachelor 60'), ('bachelor_30', 'Bachelor 30'), ('lehramt_vertieft', 'Lehramt Vertieft'), ('lehramt_nicht_vertieft', 'Lehramt Nicht Vertieft'), ('lehramt_mittelschule', 'Lehramt Mittelschule'), ('lehramt_grundschule', 'Lehramt Grundschule'), ('master_hg', 'Master Humangeographie'), ('master_pg', 'Master physische Geographie')], max_length=30),
        ),
    ]
