# Generated by Django 5.2.1 on 2025-07-16 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0011_module_responsible_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the certificate group', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this group')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in selection lists')),
            ],
            options={
                'verbose_name': 'Certificate Group',
                'verbose_name_plural': 'Certificate Groups',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='modulecertificate',
            name='global_operator',
            field=models.CharField(choices=[('and', 'UND'), ('or', 'ODER')], default='and', help_text='How certificate groups should be combined', max_length=3),
        ),
        migrations.AlterField(
            model_name='modulecertificate',
            name='logic_operator',
            field=models.CharField(choices=[('and', 'UND'), ('or', 'ODER')], default='or', help_text='Legacy: How selected options should be combined', max_length=3),
        ),
        migrations.AlterField(
            model_name='modulecertificate',
            name='selected_options',
            field=models.ManyToManyField(blank=True, help_text='Legacy: Select multiple certificate options', to='studyprogrammes_v2.certificateoption'),
        ),
        migrations.CreateModel(
            name='ModuleCertificateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_operator', models.CharField(choices=[('and', 'UND'), ('or', 'ODER')], default='or', help_text='How options within this group should be combined', max_length=3)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the certificate')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyprogrammes_v2.certificategroup')),
                ('module_certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_groups', to='studyprogrammes_v2.modulecertificate')),
                ('selected_options', models.ManyToManyField(blank=True, help_text='Selected options for this group', to='studyprogrammes_v2.certificateoption')),
            ],
            options={
                'verbose_name': 'Module Certificate Group',
                'verbose_name_plural': 'Module Certificate Groups',
                'ordering': ['order', 'group__name'],
                'unique_together': {('module_certificate', 'group')},
            },
        ),
    ]
