# Generated by Django 5.2.1 on 2025-07-16 12:47

from django.db import migrations


def create_default_certificate_groups(apps, schema_editor):
    """Create default certificate groups for common use cases."""
    CertificateGroup = apps.get_model('studyprogrammes_v2', 'CertificateGroup')
    
    default_groups = [
        {'name': 'Schriftliche Prüfung', 'description': 'Klausuren, Tests, schriftliche Arbeiten', 'order': 1},
        {'name': 'Praktische Arbeit', 'description': 'Laborberichte, Projekte, praktische Übungen', 'order': 2},
        {'name': 'Mündliche Prüfung', 'description': 'Präsentationen, mündliche Prüfungen', 'order': 3},
        {'name': 'Kontinuierliche Bewertung', 'description': 'Mitarbeit, Anwesenheit, regelmäßige Abgaben', 'order': 4},
        {'name': 'Wissenschaftliche Arbeit', 'description': 'Hausarbeiten, Essays, Forschungsarbeiten', 'order': 5},
    ]
    
    for group_data in default_groups:
        CertificateGroup.objects.get_or_create(
            name=group_data['name'],
            defaults={
                'description': group_data['description'],
                'order': group_data['order']
            }
        )


def reverse_default_certificate_groups(apps, schema_editor):
    """Remove default certificate groups."""
    CertificateGroup = apps.get_model('studyprogrammes_v2', 'CertificateGroup')
    
    default_names = [
        'Schriftliche Prüfung',
        'Praktische Arbeit', 
        'Mündliche Prüfung',
        'Kontinuierliche Bewertung',
        'Wissenschaftliche Arbeit'
    ]
    
    CertificateGroup.objects.filter(name__in=default_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0012_certificategroup_modulecertificate_global_operator_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_certificate_groups, reverse_default_certificate_groups),
    ]
