# Generated by Django 5.2.1 on 2025-07-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0013_auto_20250716_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulecertificate',
            name='group_structure',
            field=models.JSONField(blank=True, default=dict, help_text='Complete group structure with options, operators, and order', null=True),
        ),
    ]
