# Generated by Django 5.2.1 on 2025-07-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0014_add_group_structure_to_modulecertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='qualification_goals',
            field=models.TextField(blank=True, help_text='Qualification goals and learning outcomes for this module', null=True),
        ),
    ]
