# Generated by Django 5.2.1 on 2025-07-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0014_programme_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='certificate',
            field=models.TextField(blank=True, help_text='Certificate or qualification information for this module'),
        ),
    ]
