# Generated by Django 5.2.1 on 2025-07-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0015_module_qualification_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='certificate',
        ),
    ]
