# Generated by Django 5.2.1 on 2025-07-13 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0015_module_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Whether this course is shared with other users'),
        ),
        migrations.AddField(
            model_name='course',
            name='original_course',
            field=models.ForeignKey(blank=True, help_text='Reference to original course if this is a shared copy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_copies', to='studyprogrammes_v2.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='shared_at',
            field=models.DateTimeField(blank=True, help_text='When this course was shared', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='shared_by',
            field=models.ForeignKey(blank=True, help_text='Original creator who shared this course', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_courses_v2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programme',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Whether this programme is shared with other users'),
        ),
        migrations.AddField(
            model_name='programme',
            name='original_programme',
            field=models.ForeignKey(blank=True, help_text='Reference to original programme if this is a shared copy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_copies', to='studyprogrammes_v2.programme'),
        ),
        migrations.AddField(
            model_name='programme',
            name='shared_at',
            field=models.DateTimeField(blank=True, help_text='When this programme was shared', null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='shared_by',
            field=models.ForeignKey(blank=True, help_text='Original creator who shared this programme', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_programmes_v2', to=settings.AUTH_USER_MODEL),
        ),
    ]
