# Generated by Django 5.2.1 on 2025-09-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyprogrammes_v2', '0016_remove_legacy_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulecertificate',
            name='logic_operator',
        ),
        migrations.RemoveField(
            model_name='modulecertificate',
            name='selected_options',
        ),
        migrations.AlterField(
            model_name='defaultnebenfach',
            name='programme_type',
            field=models.CharField(choices=[('bachelor_100', 'Bachelor'), ('bachelor_60', 'Bachelor 60'), ('bachelor_30', 'Bachelor 30'), ('lehramt_vertieft', 'Lehramt Vertieft'), ('lehramt_nicht_vertieft', 'Lehramt Nicht Vertieft'), ('lehramt_mittelschule', 'Lehramt Mittelschule'), ('lehramt_grundschule', 'Lehramt Grundschule'), ('didaktik_grundschule', 'Didaktik Grundschule'), ('didaktik_mittelschule', 'Didaktik Mittelschule'), ('didaktik_sonderpaedagogik', 'Didaktik Sonderpädagogik'), ('master_hg', 'Master Humangeographie'), ('master_pg', 'Master Physische Geographie')], max_length=30),
        ),
        migrations.AlterField(
            model_name='defaultstudentcount',
            name='programme_type',
            field=models.CharField(choices=[('bachelor_100', 'Bachelor'), ('bachelor_60', 'Bachelor 60'), ('bachelor_30', 'Bachelor 30'), ('lehramt_vertieft', 'Lehramt Vertieft'), ('lehramt_nicht_vertieft', 'Lehramt Nicht Vertieft'), ('lehramt_mittelschule', 'Lehramt Mittelschule'), ('lehramt_grundschule', 'Lehramt Grundschule'), ('didaktik_grundschule', 'Didaktik Grundschule'), ('didaktik_mittelschule', 'Didaktik Mittelschule'), ('didaktik_sonderpaedagogik', 'Didaktik Sonderpädagogik'), ('master_hg', 'Master Humangeographie'), ('master_pg', 'Master Physische Geographie')], max_length=30),
        ),
        migrations.AlterField(
            model_name='programme',
            name='programme_type',
            field=models.CharField(choices=[('bachelor_100', 'Bachelor'), ('bachelor_60', 'Bachelor 60'), ('bachelor_30', 'Bachelor 30'), ('lehramt_vertieft', 'Lehramt Vertieft'), ('lehramt_nicht_vertieft', 'Lehramt Nicht Vertieft'), ('lehramt_mittelschule', 'Lehramt Mittelschule'), ('lehramt_grundschule', 'Lehramt Grundschule'), ('didaktik_grundschule', 'Didaktik Grundschule'), ('didaktik_mittelschule', 'Didaktik Mittelschule'), ('didaktik_sonderpaedagogik', 'Didaktik Sonderpädagogik'), ('master_hg', 'Master Humangeographie'), ('master_pg', 'Master Physische Geographie')], max_length=30),
        ),
    ]
